version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
